// Code generated by MockGen. DO NOT EDIT.
// Source: 2021_2_MAMBa/internal/pkg/domain (interfaces: FilmUsecase)

// Package mock is a generated GoMock package.
package mock

import (
	domain "2021_2_MAMBa/internal/pkg/domain"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockFilmUsecase is a mock of FilmUsecase interface.
type MockFilmUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockFilmUsecaseMockRecorder
}

// MockFilmUsecaseMockRecorder is the mock recorder for MockFilmUsecase.
type MockFilmUsecaseMockRecorder struct {
	mock *MockFilmUsecase
}

// NewMockFilmUsecase creates a new mock instance.
func NewMockFilmUsecase(ctrl *gomock.Controller) *MockFilmUsecase {
	mock := &MockFilmUsecase{ctrl: ctrl}
	mock.recorder = &MockFilmUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFilmUsecase) EXPECT() *MockFilmUsecaseMockRecorder {
	return m.recorder
}

// GetFilm mocks base method.
func (m *MockFilmUsecase) GetFilm(arg0 uint64, arg1, arg2, arg3, arg4 int) (domain.FilmPageInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFilm", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].(domain.FilmPageInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFilm indicates an expected call of GetFilm.
func (mr *MockFilmUsecaseMockRecorder) GetFilm(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFilm", reflect.TypeOf((*MockFilmUsecase)(nil).GetFilm), arg0, arg1, arg2, arg3, arg4)
}

// LoadFilmRecommendations mocks base method.
func (m *MockFilmUsecase) LoadFilmRecommendations(arg0 uint64, arg1, arg2 int) (domain.FilmRecommendations, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadFilmRecommendations", arg0, arg1, arg2)
	ret0, _ := ret[0].(domain.FilmRecommendations)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadFilmRecommendations indicates an expected call of LoadFilmRecommendations.
func (mr *MockFilmUsecaseMockRecorder) LoadFilmRecommendations(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadFilmRecommendations", reflect.TypeOf((*MockFilmUsecase)(nil).LoadFilmRecommendations), arg0, arg1, arg2)
}

// LoadFilmReviews mocks base method.
func (m *MockFilmUsecase) LoadFilmReviews(arg0 uint64, arg1, arg2 int) (domain.FilmReviews, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadFilmReviews", arg0, arg1, arg2)
	ret0, _ := ret[0].(domain.FilmReviews)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadFilmReviews indicates an expected call of LoadFilmReviews.
func (mr *MockFilmUsecaseMockRecorder) LoadFilmReviews(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadFilmReviews", reflect.TypeOf((*MockFilmUsecase)(nil).LoadFilmReviews), arg0, arg1, arg2)
}

// LoadMyReview mocks base method.
func (m *MockFilmUsecase) LoadMyReview(arg0, arg1 uint64) (domain.Review, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadMyReview", arg0, arg1)
	ret0, _ := ret[0].(domain.Review)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadMyReview indicates an expected call of LoadMyReview.
func (mr *MockFilmUsecaseMockRecorder) LoadMyReview(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadMyReview", reflect.TypeOf((*MockFilmUsecase)(nil).LoadMyReview), arg0, arg1)
}

// PostRating mocks base method.
func (m *MockFilmUsecase) PostRating(arg0, arg1 uint64, arg2 float64) (float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PostRating", arg0, arg1, arg2)
	ret0, _ := ret[0].(float64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PostRating indicates an expected call of PostRating.
func (mr *MockFilmUsecaseMockRecorder) PostRating(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PostRating", reflect.TypeOf((*MockFilmUsecase)(nil).PostRating), arg0, arg1, arg2)
}
