// Code generated by MockGen. DO NOT EDIT.
// Source: 2021_2_MAMBa/internal/pkg/domain (interfaces: PersonUsecase)

// Package mock is a generated GoMock package.
package mock

import (
	domain "2021_2_MAMBa/internal/pkg/domain"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockPersonUsecase is a mock of PersonUsecase interface.
type MockPersonUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockPersonUsecaseMockRecorder
}

// MockPersonUsecaseMockRecorder is the mock recorder for MockPersonUsecase.
type MockPersonUsecaseMockRecorder struct {
	mock *MockPersonUsecase
}

// NewMockPersonUsecase creates a new mock instance.
func NewMockPersonUsecase(ctrl *gomock.Controller) *MockPersonUsecase {
	mock := &MockPersonUsecase{ctrl: ctrl}
	mock.recorder = &MockPersonUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPersonUsecase) EXPECT() *MockPersonUsecaseMockRecorder {
	return m.recorder
}

// GetFilms mocks base method.
func (m *MockPersonUsecase) GetFilms(arg0 uint64, arg1, arg2 int) (domain.FilmList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFilms", arg0, arg1, arg2)
	ret0, _ := ret[0].(domain.FilmList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFilms indicates an expected call of GetFilms.
func (mr *MockPersonUsecaseMockRecorder) GetFilms(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFilms", reflect.TypeOf((*MockPersonUsecase)(nil).GetFilms), arg0, arg1, arg2)
}

// GetPerson mocks base method.
func (m *MockPersonUsecase) GetPerson(arg0 uint64) (domain.PersonPage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPerson", arg0)
	ret0, _ := ret[0].(domain.PersonPage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPerson indicates an expected call of GetPerson.
func (mr *MockPersonUsecaseMockRecorder) GetPerson(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPerson", reflect.TypeOf((*MockPersonUsecase)(nil).GetPerson), arg0)
}
