// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package domain

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonDb0593a3Decode20212MAMBaInternalPkgDomain(in *jlexer.Lexer, out *PersonPage) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "actor":
			(out.Actor).UnmarshalEasyJSON(in)
		case "films":
			(out.Films).UnmarshalEasyJSON(in)
		case "popular_films":
			(out.PopularFilms).UnmarshalEasyJSON(in)
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonDb0593a3Encode20212MAMBaInternalPkgDomain(out *jwriter.Writer, in PersonPage) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"actor\":"
		out.RawString(prefix[1:])
		(in.Actor).MarshalEasyJSON(out)
	}
	{
		const prefix string = ",\"films\":"
		out.RawString(prefix)
		(in.Films).MarshalEasyJSON(out)
	}
	{
		const prefix string = ",\"popular_films\":"
		out.RawString(prefix)
		(in.PopularFilms).MarshalEasyJSON(out)
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v PersonPage) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonDb0593a3Encode20212MAMBaInternalPkgDomain(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v PersonPage) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonDb0593a3Encode20212MAMBaInternalPkgDomain(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *PersonPage) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonDb0593a3Decode20212MAMBaInternalPkgDomain(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *PersonPage) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonDb0593a3Decode20212MAMBaInternalPkgDomain(l, v)
}
func easyjsonDb0593a3Decode20212MAMBaInternalPkgDomain1(in *jlexer.Lexer, out *PersonList) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "person_list":
			if in.IsNull() {
				in.Skip()
				out.PersonList = nil
			} else {
				in.Delim('[')
				if out.PersonList == nil {
					if !in.IsDelim(']') {
						out.PersonList = make([]Person, 0, 0)
					} else {
						out.PersonList = []Person{}
					}
				} else {
					out.PersonList = (out.PersonList)[:0]
				}
				for !in.IsDelim(']') {
					var v1 Person
					(v1).UnmarshalEasyJSON(in)
					out.PersonList = append(out.PersonList, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "more_available":
			out.MoreAvailable = bool(in.Bool())
		case "person_total":
			out.PersonTotal = int(in.Int())
		case "current_limit":
			out.CurrentLimit = int(in.Int())
		case "current_skip":
			out.CurrentSkip = int(in.Int())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonDb0593a3Encode20212MAMBaInternalPkgDomain1(out *jwriter.Writer, in PersonList) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"person_list\":"
		out.RawString(prefix[1:])
		if in.PersonList == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v2, v3 := range in.PersonList {
				if v2 > 0 {
					out.RawByte(',')
				}
				(v3).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"more_available\":"
		out.RawString(prefix)
		out.Bool(bool(in.MoreAvailable))
	}
	{
		const prefix string = ",\"person_total\":"
		out.RawString(prefix)
		out.Int(int(in.PersonTotal))
	}
	{
		const prefix string = ",\"current_limit\":"
		out.RawString(prefix)
		out.Int(int(in.CurrentLimit))
	}
	{
		const prefix string = ",\"current_skip\":"
		out.RawString(prefix)
		out.Int(int(in.CurrentSkip))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v PersonList) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonDb0593a3Encode20212MAMBaInternalPkgDomain1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v PersonList) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonDb0593a3Encode20212MAMBaInternalPkgDomain1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *PersonList) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonDb0593a3Decode20212MAMBaInternalPkgDomain1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *PersonList) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonDb0593a3Decode20212MAMBaInternalPkgDomain1(l, v)
}
func easyjsonDb0593a3Decode20212MAMBaInternalPkgDomain2(in *jlexer.Lexer, out *Person) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			out.Id = uint64(in.Uint64())
		case "name_en":
			out.NameEn = string(in.String())
		case "name_rus":
			out.NameRus = string(in.String())
		case "picture_url":
			out.PictureUrl = string(in.String())
		case "career":
			if in.IsNull() {
				in.Skip()
				out.Career = nil
			} else {
				in.Delim('[')
				if out.Career == nil {
					if !in.IsDelim(']') {
						out.Career = make([]string, 0, 4)
					} else {
						out.Career = []string{}
					}
				} else {
					out.Career = (out.Career)[:0]
				}
				for !in.IsDelim(']') {
					var v4 string
					v4 = string(in.String())
					out.Career = append(out.Career, v4)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "height":
			out.Height = float64(in.Float64())
		case "age":
			out.Age = int(in.Int())
		case "birthday":
			out.Birthday = string(in.String())
		case "death":
			out.Death = string(in.String())
		case "birth_place":
			out.BirthPlace = string(in.String())
		case "death_place":
			out.DeathPlace = string(in.String())
		case "gender":
			out.Gender = string(in.String())
		case "family_status":
			out.FamilyStatus = string(in.String())
		case "film_number":
			out.FilmNumber = int(in.Int())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonDb0593a3Encode20212MAMBaInternalPkgDomain2(out *jwriter.Writer, in Person) {
	out.RawByte('{')
	first := true
	_ = first
	if in.Id != 0 {
		const prefix string = ",\"id\":"
		first = false
		out.RawString(prefix[1:])
		out.Uint64(uint64(in.Id))
	}
	if in.NameEn != "" {
		const prefix string = ",\"name_en\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.NameEn))
	}
	if in.NameRus != "" {
		const prefix string = ",\"name_rus\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.NameRus))
	}
	if in.PictureUrl != "" {
		const prefix string = ",\"picture_url\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.PictureUrl))
	}
	if len(in.Career) != 0 {
		const prefix string = ",\"career\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		{
			out.RawByte('[')
			for v5, v6 := range in.Career {
				if v5 > 0 {
					out.RawByte(',')
				}
				out.String(string(v6))
			}
			out.RawByte(']')
		}
	}
	if in.Height != 0 {
		const prefix string = ",\"height\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Float64(float64(in.Height))
	}
	if in.Age != 0 {
		const prefix string = ",\"age\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int(int(in.Age))
	}
	if in.Birthday != "" {
		const prefix string = ",\"birthday\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Birthday))
	}
	if in.Death != "" {
		const prefix string = ",\"death\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Death))
	}
	if in.BirthPlace != "" {
		const prefix string = ",\"birth_place\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.BirthPlace))
	}
	if in.DeathPlace != "" {
		const prefix string = ",\"death_place\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.DeathPlace))
	}
	if in.Gender != "" {
		const prefix string = ",\"gender\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Gender))
	}
	if in.FamilyStatus != "" {
		const prefix string = ",\"family_status\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.FamilyStatus))
	}
	if in.FilmNumber != 0 {
		const prefix string = ",\"film_number\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int(int(in.FilmNumber))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Person) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonDb0593a3Encode20212MAMBaInternalPkgDomain2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Person) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonDb0593a3Encode20212MAMBaInternalPkgDomain2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Person) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonDb0593a3Decode20212MAMBaInternalPkgDomain2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Person) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonDb0593a3Decode20212MAMBaInternalPkgDomain2(l, v)
}
func easyjsonDb0593a3Decode20212MAMBaInternalPkgDomain3(in *jlexer.Lexer, out *FilmList) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "film_list":
			if in.IsNull() {
				in.Skip()
				out.FilmList = nil
			} else {
				in.Delim('[')
				if out.FilmList == nil {
					if !in.IsDelim(']') {
						out.FilmList = make([]Film, 0, 0)
					} else {
						out.FilmList = []Film{}
					}
				} else {
					out.FilmList = (out.FilmList)[:0]
				}
				for !in.IsDelim(']') {
					var v7 Film
					easyjsonDb0593a3Decode20212MAMBaInternalPkgDomain4(in, &v7)
					out.FilmList = append(out.FilmList, v7)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "more_available":
			out.MoreAvailable = bool(in.Bool())
		case "film_total":
			out.FilmTotal = int(in.Int())
		case "current_limit":
			out.CurrentLimit = int(in.Int())
		case "current_skip":
			out.CurrentSkip = int(in.Int())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonDb0593a3Encode20212MAMBaInternalPkgDomain3(out *jwriter.Writer, in FilmList) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"film_list\":"
		out.RawString(prefix[1:])
		if in.FilmList == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v8, v9 := range in.FilmList {
				if v8 > 0 {
					out.RawByte(',')
				}
				out.Raw((v9).MarshalJSON())
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"more_available\":"
		out.RawString(prefix)
		out.Bool(bool(in.MoreAvailable))
	}
	{
		const prefix string = ",\"film_total\":"
		out.RawString(prefix)
		out.Int(int(in.FilmTotal))
	}
	{
		const prefix string = ",\"current_limit\":"
		out.RawString(prefix)
		out.Int(int(in.CurrentLimit))
	}
	{
		const prefix string = ",\"current_skip\":"
		out.RawString(prefix)
		out.Int(int(in.CurrentSkip))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v FilmList) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonDb0593a3Encode20212MAMBaInternalPkgDomain3(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v FilmList) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonDb0593a3Encode20212MAMBaInternalPkgDomain3(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *FilmList) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonDb0593a3Decode20212MAMBaInternalPkgDomain3(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *FilmList) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonDb0593a3Decode20212MAMBaInternalPkgDomain3(l, v)
}
func easyjsonDb0593a3Decode20212MAMBaInternalPkgDomain4(in *jlexer.Lexer, out *Film) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			out.Id = uint64(in.Uint64())
		case "title":
			out.Title = string(in.String())
		case "title_original":
			out.TitleOriginal = string(in.String())
		case "rating":
			out.Rating = float64(in.Float64())
		case "description":
			out.Description = string(in.String())
		case "total_revenue":
			out.TotalRevenue = string(in.String())
		case "poster_url":
			out.PosterUrl = string(in.String())
		case "trailer_url":
			out.TrailerUrl = string(in.String())
		case "content_type":
			out.ContentType = string(in.String())
		case "release_year":
			out.ReleaseYear = int(in.Int())
		case "duration":
			out.Duration = int(in.Int())
		case "premiere_ru":
			out.PremiereRu = string(in.String())
		case "origin_countries":
			if in.IsNull() {
				in.Skip()
				out.OriginCountries = nil
			} else {
				in.Delim('[')
				if out.OriginCountries == nil {
					if !in.IsDelim(']') {
						out.OriginCountries = make([]string, 0, 4)
					} else {
						out.OriginCountries = []string{}
					}
				} else {
					out.OriginCountries = (out.OriginCountries)[:0]
				}
				for !in.IsDelim(']') {
					var v10 string
					v10 = string(in.String())
					out.OriginCountries = append(out.OriginCountries, v10)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "cast":
			if in.IsNull() {
				in.Skip()
				out.Cast = nil
			} else {
				in.Delim('[')
				if out.Cast == nil {
					if !in.IsDelim(']') {
						out.Cast = make([]Person, 0, 0)
					} else {
						out.Cast = []Person{}
					}
				} else {
					out.Cast = (out.Cast)[:0]
				}
				for !in.IsDelim(']') {
					var v11 Person
					(v11).UnmarshalEasyJSON(in)
					out.Cast = append(out.Cast, v11)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "director":
			(out.Director).UnmarshalEasyJSON(in)
		case "screenwriter":
			(out.Screenwriter).UnmarshalEasyJSON(in)
		case "genres":
			if in.IsNull() {
				in.Skip()
				out.Genres = nil
			} else {
				in.Delim('[')
				if out.Genres == nil {
					if !in.IsDelim(']') {
						out.Genres = make([]Genre, 0, 1)
					} else {
						out.Genres = []Genre{}
					}
				} else {
					out.Genres = (out.Genres)[:0]
				}
				for !in.IsDelim(']') {
					var v12 Genre
					easyjsonDb0593a3Decode20212MAMBaInternalPkgDomain5(in, &v12)
					out.Genres = append(out.Genres, v12)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonDb0593a3Encode20212MAMBaInternalPkgDomain4(out *jwriter.Writer, in Film) {
	out.RawByte('{')
	first := true
	_ = first
	if in.Id != 0 {
		const prefix string = ",\"id\":"
		first = false
		out.RawString(prefix[1:])
		out.Uint64(uint64(in.Id))
	}
	if in.Title != "" {
		const prefix string = ",\"title\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Title))
	}
	if in.TitleOriginal != "" {
		const prefix string = ",\"title_original\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.TitleOriginal))
	}
	if in.Rating != 0 {
		const prefix string = ",\"rating\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Float64(float64(in.Rating))
	}
	if in.Description != "" {
		const prefix string = ",\"description\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Description))
	}
	if in.TotalRevenue != "" {
		const prefix string = ",\"total_revenue\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.TotalRevenue))
	}
	if in.PosterUrl != "" {
		const prefix string = ",\"poster_url\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.PosterUrl))
	}
	if in.TrailerUrl != "" {
		const prefix string = ",\"trailer_url\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.TrailerUrl))
	}
	if in.ContentType != "" {
		const prefix string = ",\"content_type\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.ContentType))
	}
	if in.ReleaseYear != 0 {
		const prefix string = ",\"release_year\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int(int(in.ReleaseYear))
	}
	if in.Duration != 0 {
		const prefix string = ",\"duration\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int(int(in.Duration))
	}
	if in.PremiereRu != "" {
		const prefix string = ",\"premiere_ru\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.PremiereRu))
	}
	if len(in.OriginCountries) != 0 {
		const prefix string = ",\"origin_countries\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		{
			out.RawByte('[')
			for v13, v14 := range in.OriginCountries {
				if v13 > 0 {
					out.RawByte(',')
				}
				out.String(string(v14))
			}
			out.RawByte(']')
		}
	}
	if len(in.Cast) != 0 {
		const prefix string = ",\"cast\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		{
			out.RawByte('[')
			for v15, v16 := range in.Cast {
				if v15 > 0 {
					out.RawByte(',')
				}
				(v16).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	if true {
		const prefix string = ",\"director\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		(in.Director).MarshalEasyJSON(out)
	}
	if true {
		const prefix string = ",\"screenwriter\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		(in.Screenwriter).MarshalEasyJSON(out)
	}
	if len(in.Genres) != 0 {
		const prefix string = ",\"genres\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		{
			out.RawByte('[')
			for v17, v18 := range in.Genres {
				if v17 > 0 {
					out.RawByte(',')
				}
				easyjsonDb0593a3Encode20212MAMBaInternalPkgDomain5(out, v18)
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}
func easyjsonDb0593a3Decode20212MAMBaInternalPkgDomain5(in *jlexer.Lexer, out *Genre) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			out.Id = uint64(in.Uint64())
		case "name":
			out.Name = string(in.String())
		case "picture_url":
			out.PictureURL = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonDb0593a3Encode20212MAMBaInternalPkgDomain5(out *jwriter.Writer, in Genre) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.Uint64(uint64(in.Id))
	}
	{
		const prefix string = ",\"name\":"
		out.RawString(prefix)
		out.String(string(in.Name))
	}
	if in.PictureURL != "" {
		const prefix string = ",\"picture_url\":"
		out.RawString(prefix)
		out.String(string(in.PictureURL))
	}
	out.RawByte('}')
}
