DROP DATABASE IF EXISTS Film4U;
DROP ROLE IF EXISTS dev;
CREATE ROLE dev WITH PASSWORD '1234';
ALTER ROLE dev WITH LOGIN superuser;
CREATE DATABASE Film4U
    WITH
    OWNER = dev
    ENCODING = 'UTF8'
    TABLESPACE = pg_default
    CONNECTION LIMIT = -1;

